### ISSUE TITLE
مشكلة فى البحث مع سيجما

### ISSUE THREAD

**Issue by Ticno98** [amkige/pcprices#1]
كل لما اسيرش على حاجة سيجما بيطلع اول ستور و بيكون فيه حاجات ملهاش علاقة باللى عملت بيه سيرش
![Capture](https://user-images.githubusercontent.com/77648296/119721942-0dab2f00-be6c-11eb-84e3-f278334a4c18.PNG)

**Comment by amkige** [comment]
المشكلة اتحلت
